#!/usr/bin/env python
# -*- coding:utf-8 -

import requests
import re

while True:
    city = input()
    if city == 'q':
        print('您已经退出该程序！')
        break
    else:
        # response = requests.get('http://www.pm25x.com/city/qingdao.htm')
        response = requests.get('http://www.pm25x.com/city/'+city+'.htm')
        html = response.text
        result_li = re.findall('<tr>.*?<td>(\w+)</td>.*?<td>(\w+)</td>.*?<span>(\w+)</span>.*?</tr>',html,re.S)
        for i in result_li:
            print(i[0],i[1],i[2])
