#!/usr/bin/env python
# -*- coding:utf-8 -*-

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import StaleElementReferenceException
from pyquery import PyQuery as pq
import pymongo


def ToMongoDB(data):
    client = pymongo.MongoClient(host = 'localhost',port = 27017)
    db = client.TaoBao
    collection = db.Ipad
    collection.insert(data)


def ParesePage(html):
    doc = pq(html)
    items = doc('div.items div.J_MouserOnverReq').items()
    for item in items:
        img = item.find('div.pic-box-inner a.pic.link img.img').attr('data-src')
        shop = item.find('div.shop span.dsrs.span').text()
        location = item.find('div.location').text()
        name = item.find('div.ctx-box a.J_ClickStat').text()
        data = {
            # 'deal_cnt':str(deal_cnt),
            'img':str(img),
            'shop':shop,
            'location':location,
            'name':name
        }
        ToMongoDB(data)


if __name__ == "__main__":
    KEYWORD = input("please input the search name:")
    flag = int(input("Mode-Selection:"))
    page_index = 1
    if flag == 0:
        print('you have entered the borderless mode,please wait......')
        firefox_options = webdriver.FirefoxOptions()
        firefox_options.add_argument('--headless')
        browser = webdriver.Firefox(firefox_options = firefox_options)
    elif flag == 1:
        print('you have entered the border mode,please wait......')
        browser = webdriver.Firefox()
        browser.maximize_window()
    browser.get('https://www.taobao.com/')
    input = browser.find_element_by_id('q')
    input.send_keys(KEYWORD)
    btn = browser.find_element_by_class_name('btn-search')
    btn.click()
    # wait = WebDriverWait(browser,10)
    # total_page = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR,'div.pager ul.items li.item a.link')))
    total_page_str = browser.find_element_by_css_selector('div.pager ul.items li.item:nth-child(2)')
    total_page = int(total_page_str.text.split('/')[1])
    # print(total_page)

    while page_index <= total_page:
        print('spider page: '+str(page_index)+'......')
        page_index += 1
        ParesePage(browser.page_source)

        # print(data)
        wait = WebDriverWait(browser,10)
        try:
            input = wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR,'input.J_Input')))
            # input = browser.find_element_by_css_selector('input.J_Input')
            input.clear()
            input.send_keys(page_index)
            btn = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR,'span.J_Submit')))
            # btn = browser.find_element_by_css_selector('span.J_Submit')
            btn.click()
        except StaleElementReferenceException:
            browser.refresh()
            page_index -= 1

    print('Over!')
    browser.close()


